# Generated by Django 5.0.7 on 2024-07-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
