# Generated by Django 5.0.7 on 2024-07-30 11:12

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='static/images/profile1.jpg', force_format='PNG', help_text='size of logo must be 250*250 and format must be png image file', keep_meta=True, null=True, quality=75, scale=None, size=[250, 250], upload_to='accounts/images/profiles/'),
        ),
    ]
